### ISSUE TITLE
`svgcheck` 0.7.0 dropped `-X`

### ISSUE THREAD

**Issue by larseggert** [martinthomson/i-d-template#364]
See https://github.com/ietf-tools/svgcheck/pull/32.

**Comment by snorp** [comment]
Yeah, and in `0.7.1` there doesn't even seem to be an error printed for that? I get the following right now.

```
** Not using persistent HTTP -- cannot load such file -- net/http/persistent
**   To silence this message and get full speed, try:
**     gem install net-http-persistent
**   If this doesn't work, you can ignore this warning.
*** [svgcheck:] Traceback (most recent call last):
*** [svgcheck:]   File "/usr/local/google/home/jwillcox/tigress/lib/.venv/bin/svgcheck", line 8, in <module>
*** [svgcheck:]     sys.exit(main())
*** [svgcheck:]   File "/usr/local/google/home/jwillcox/tigress/lib/.venv/lib/python3.10/site-packages/svgcheck/run.py", line 122, in main
*** [svgcheck:]     parser = XmlRfcParser(source, verbose=options.verbose,
*** [svgcheck:]   File "/usr/local/google/home/jwillcox/tigress/lib/.venv/lib/python3.10/site-packages/xml2rfc/parser.py", line 500, in __init__
*** [svgcheck:]     with io.open(self.source, "rb", newline=None) as f:
*** [svgcheck:] FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/google/home/jwillcox/tigress/stdin'
*** could not create svg for "       ┌──────┐    ...
Error: Unable to parse the XML document: /dev/stdin
```

We should follow up with `kramdown-rfc`, but for now maybe we should just lock to the last known-good version, `0.6.2`.

**Comment by snorp** [comment]
https://github.com/cabo/kramdown-rfc/issues/187

**Comment by snorp** [comment]
The error above is a separate regression in `svgcheck`. It has been worked around in the latest `kramdown-rfc`, but it looks like we need to rebuild the Docker images to get that. @martinthomson can you kick something?

**Comment by martinthomson** [comment]
Boot applied.  Should be good in about 10 minutes, slightly longer if there is a build failure and I have to kick it again.
